name: automationCorePrototype
description: A home automation controller written in Dart communicating over MQTT.
# version: 1.0.0
# homepage: https://isaacparker.co
# author: isaac <parrotmac@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  mqtt_client: ^5.1.0
  json_annotation: ^2.0.0
  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  test: ^1.0.0
